version: '3'
services:
  oai-gnb:
    image: oaisoftwarealliance/oai-gnb:develop
    privileged: true
    container_name: oai-gnb
    environment:
      USE_ADDITIONAL_OPTIONS: --gNBs.\[0\].min_rxtxtime 6 --rfsim --sa
    volumes:
      - ./gnb.conf:/opt/oai-gnb/etc/gnb.conf
    healthcheck:
      test: /bin/bash -c "pgrep nr-softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host
